import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import styles from './homePage.module.css'
import SignIn from "@repo/ui/SignIn";
import Signup from "@repo/ui/SignUp";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
    href="https://cdn.jsdelivr.net/npm/remixicon@4.5.0/fonts/remixicon.css"
    rel="stylesheet"/>
    <link href ="https://fonts.cdnfonts.com/css/gilroy" rel="stylesheet"></link>

      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        
      <nav className = {styles.nav}>
            <a className = {styles.elem} href='/'>Home</a>
            <a className = {styles.elem} href='#'>About</a>
            <a className = {styles.elem} href='#'>Cart</a>
            
                <Signup/>
                <SignIn/>
           
            <a className = {styles.elem}><i className="ri-shopping-bag-4-fill"></i></a>
            </nav>
        {children}
      </body>
    </html>
  );
}
